"""
Tetris configuration values.
"""

GRID_WIDTH = 10
GRID_HEIGHT = 20
CELL_SIZE = 32

SCREEN_WIDTH = GRID_WIDTH * CELL_SIZE
SCREEN_HEIGHT = GRID_HEIGHT * CELL_SIZE

BACKGROUND_COLOR = (15, 15, 15)
GRID_COLOR = (40, 40, 40)
